// Run the user's OpenMC deck just far enough to write geometry.xml (and
// materials.xml when present). The in-editor 3D/2D viewers parse that XML
// instead of guessing at Python. Same loader as "Render with OpenMC".
import { execFile } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as vscode from 'vscode';
import { OPENMC_DECK_LOADER_PY } from './deckLoader';
import { buildRenderRequest } from './core';
import { readDeckOptions, resolveOpenmcInterpreter, translatePathForCandidate } from './detect';

const EXPORT_TIMEOUT_MS = 180_000;

const EXPORT_HELPER = `# Generated by OWEN ("export geometry for the in-editor preview"). Safe to delete.
import json, os, sys, traceback
${OPENMC_DECK_LOADER_PY}

def main():
    with open(sys.argv[1], 'r') as fh:
        req = json.load(fh)
    out_dir = req['outDir']
    result = {'ok': False, 'error': None, 'warnings': [], 'source': None}
    try:
        ctx = owen_load_deck(req, out_dir, result['warnings'], 'geometry-export pass')
        result['source'] = ctx.get('source')
        geometry = ctx.get('geometry')
        materials = ctx.get('materials')
        export = ctx.get('realGeometryExport')
        if geometry is not None and export:
            export(geometry, out_dir)
        elif geometry is not None and hasattr(geometry, 'export_to_xml'):
            geometry.export_to_xml(out_dir)
        if materials is not None and hasattr(materials, 'export_to_xml'):
            try:
                materials.export_to_xml(out_dir)
            except Exception:
                result['warnings'].append('materials.xml export failed; cells will be uncoloured.')
        geom_path = os.path.join(out_dir, 'geometry.xml')
        result['ok'] = os.path.exists(geom_path)
        if not result['ok']:
            result['error'] = 'OpenMC wrote no geometry.xml after loading the deck.'
    except Exception:
        result['error'] = traceback.format_exc()
    with open(os.path.join(out_dir, 'owen_export.json'), 'w') as fh:
        json.dump(result, fh, indent=1)
    sys.exit(0 if result['ok'] else 3)

if __name__ == '__main__':
    main()
`;

export interface ExportedOpenmcXml {
    geometryXml: string;
    materialsXml?: string;
    source?: string;
    warnings: string[];
}

export async function exportOpenmcGeometryXml(
    deckPath: string,
    resource?: vscode.Uri,
): Promise<ExportedOpenmcXml> {
    const resolved = await resolveOpenmcInterpreter(resource);
    if (!resolved) {
        throw new Error('No Python interpreter with OpenMC was found.');
    }
    const outDir = fs.mkdtempSync(path.join(os.tmpdir(), 'owen-geom-'));
    const scriptPath = path.join(outDir, 'owen_export_geometry.py');
    fs.writeFileSync(scriptPath, EXPORT_HELPER, 'utf8');
    const opts = readDeckOptions(resource);
    const request = buildRenderRequest(
        await translatePathForCandidate(resolved.candidate, deckPath),
        await translatePathForCandidate(resolved.candidate, outDir),
        [],
        opts,
    );
    const requestPath = path.join(outDir, 'owen_request.json');
    fs.writeFileSync(requestPath, JSON.stringify(request, null, 1), 'utf8');
    const args = [
        ...resolved.candidate.argsPrefix,
        await translatePathForCandidate(resolved.candidate, scriptPath),
        await translatePathForCandidate(resolved.candidate, requestPath),
    ];
    await new Promise<void>((resolve, reject) => {
        execFile(
            resolved.candidate.command,
            args,
            { timeout: EXPORT_TIMEOUT_MS, windowsHide: true, maxBuffer: 16 * 1024 * 1024 },
            (err) => {
                if (err && !fs.existsSync(path.join(outDir, 'owen_export.json'))) {
                    reject(new Error(`OpenMC geometry export failed: ${err.message}`));
                } else {
                    resolve();
                }
            },
        );
    });
    const metaPath = path.join(outDir, 'owen_export.json');
    const geomPath = path.join(outDir, 'geometry.xml');
    const matPath = path.join(outDir, 'materials.xml');
    if (!fs.existsSync(geomPath)) {
        const meta = fs.existsSync(metaPath) ? fs.readFileSync(metaPath, 'utf8') : '';
        throw new Error(`OpenMC wrote no geometry.xml. ${meta.slice(0, 800)}`);
    }
    const geometryXml = fs.readFileSync(geomPath, 'utf8');
    const materialsXml = fs.existsSync(matPath) ? fs.readFileSync(matPath, 'utf8') : undefined;
    let warnings: string[] = [];
    let source: string | undefined;
    if (fs.existsSync(metaPath)) {
        try {
            const meta = JSON.parse(fs.readFileSync(metaPath, 'utf8')) as { warnings?: string[]; source?: string };
            warnings = Array.isArray(meta.warnings) ? meta.warnings.map(String) : [];
            source = typeof meta.source === 'string' ? meta.source : undefined;
        } catch { /* ignore */ }
    }
    try { fs.rmSync(outDir, { recursive: true, force: true }); } catch { /* keep XML in memory */ }
    return { geometryXml, materialsXml, source, warnings };
}
